extends: ["eslint:recommended", "prettier"]

plugins: ["prettier"]

env:
    browser: true
    node: true
    es6: true

ignorePatterns: ["dist/"]

rules:
    "prettier/prettier": "error"
    camelcase: ["error"]
    eqeqeq: ["error"]

parserOptions:
    sourceType: "module"
