extends: ["stylelint-config-standard-scss", "stylelint-config-prettier-scss"]
rules:
    selector-class-pattern: null
    declaration-empty-line-before: null
    alpha-value-notation: null
    color-function-notation: null
ignoreShorthands: ["/flex/"]
